version: "3.8"

services:
  wazuh:
    image: wazuh/wazuh:4.9.0
    container_name: wazuh
    ports:
      - "1514:1514/udp"
      - "55000:55000/tcp"
    volumes:
      - ./wazuh/config:/var/ossec/etc
      - ./wazuh/rules:/var/ossec/rules
    environment:
      - WAZUH_PASSWORD=\${WAZUH_PASSWORD}

  shuffle:
    image: frikky/shuffle:latest
    container_name: shuffle
    ports:
      - "3001:3001"
    depends_on:
      - wazuh

  misp:
    image: coolacid/misp-docker:latest
    container_name: misp
    ports:
      - "8443:443"
    volumes:
      - ./misp/config:/var/www/MISP/app/Config

  iris:
    image: certmichelin/iris-web:latest
    container_name: iris
    ports:
      - "8000:8000"
    depends_on:
      - misp
      - wazuh

networks:
  default:
    name: sair_network
